### ISSUE TITLE
Many fake entries

### ISSUE THREAD

**Issue by tflidd** [segler-alex/radiobrowser#92] opened 2018-04-20 07:48 UTC
Someone hacked your list with many fake entries:
![image](https://user-images.githubusercontent.com/8111200/39037165-f8a6e8f6-447f-11e8-8ca5-c4ac241095fe.png)
reported downstream here: https://help.nextcloud.com/t/has-the-radio-app-been-hacked/30633

**Comment by segler-alex** [comment] 2018-04-20 09:30
duplicate of https://github.com/segler-alex/radiobrowser-api/issues/39

**Closed by segler-alex** 2018-04-20 09:30 UTC
