### ISSUE TITLE
Ability to edit/update radio stations information, icons etc.

### ISSUE THREAD

**Issue by aha999** [segler-alex/radiobrowser#236] opened 2021-01-03 13:29 UTC
There is currently no Edit feature for radio stations that i'm aware of.

Reasons for that would be the ability to add, update old icons and information.

If there have been misuses of this, user login may be implemented.

For example, for my country's radio stations, i am seeing some bad resolution or outdated icons, some stations with no icons at all etc. and i would like to update that info if there was a convenient edit interface to do that.

**Comment by wolfmanfp** [comment] 2021-01-08 22:29
There will never be an edit feature, only stream owners can "edit" the stream info by editing their stream header.

**Comment by aha999** [comment] 2021-01-08 22:32
well, how am i then going to replace bad/blurred/outdated radio icons with new/ high quality ones ?

**Comment by wolfmanfp** [comment] 2021-01-08 22:33
By adding a new entry to the database. 🤷‍♂️

**Comment by aha999** [comment] 2021-01-08 22:35
will that replace the old station icon or will that add a duplicate station with a new icon, so there will be two same streaming stations ?

**Comment by wolfmanfp** [comment] 2021-01-08 22:38
It will add a duplicate station, so I personally don't recommend it. There was an edit feature before, but the dev had to disable it because of vandalism, and he is reluctant to add the feature back, and probably never will.

**Comment by aha999** [comment] 2021-03-14 20:44
would it be possible that if i added duplicates but in higher quality, could i request the old ones to be deleted and where would i request that ?
the whole going-around situation seems ridiculous

**Comment by kousu** [comment] 2021-03-21 15:24
Yeah, this is a big drag! radio-browser is really cool as a crowdsourced icecast directory -- way better than directory.xiph.org or https://directory.shoutcast.com/ -- but not allow.

This is a duplicate of https://github.com/segler-alex/radiobrowser/issues/93, https://github.com/segler-alex/radiobrowser/issues/236 and https://github.com/segler-alex/radiobrowser/issues/118, but at least last year @segler-alex wanted to track this issue at https://github.com/segler-alex/radiobrowser-api/issues/39. But now that's been closed and apparently the new tracking issue for this is: https://github.com/segler-alex/radiobrowser-api-rust/issues/49#issuecomment-578537820

The restriction was added as an anti-spam/anti-harrassment measure; one particular troll with an axe to grind ruined the database for the rest of us.

There's a lot of enthusiasm to get this fixed so if you can contribute, please do. For example, I proposed:

* https://github.com/segler-alex/radiobrowser-api/issues/39#issuecomment-488010870
* @kekukui suggested a moderator system https://github.com/segler-alex/radiobrowser-api-rust/issues/49#issuecomment-660997881
* @louis77 suggested moderating via Github PRs https://github.com/segler-alex/radiobrowser-api-rust/issues/49#issuecomment-662495924

**Closed** 2021-03-31 17:27 UTC
